project:
  type: website
  output-dir: docs

website:
  site-url: "https://albert-joonyoung-park.github.io"
  title: "Albert Park"
  navbar:
    title: "Albert Park"
    left:
#      - href: index.qmd
#        text: HOME
      - file: projects.qmd
        text: PROJECTS
      - file: blog.qmd
        text: BLOG
      - file: index.qmd
        text: ABOUT
    background: primary
    tools:
      - icon: github
        href: https://github.com/albert-joonyoung-park
      - icon: linkedin
        href: https://www.linkedin.com/in/albertjoonpark
  page-footer: 
    left: "Copyright 2024, Albert Park."
    right: 
      - icon: github
        href: https://github.com/albert-joonyoung-park
      - icon: linkedin 
        href: https://www.linkedin.com/in/albertjoonpark
    background: dark
  google-analytics: "G-STXFCZ6KQX"

format:
  html:
    theme: Zephyr
    css: styles.css
    toc: true
    fontsize: 1.1em
    html-math-method: katex

editor: visual

